### ISSUE TITLE
Serving a static folder should create a default route to an index.html file

### ISSUE THREAD

**Issue by TylerLeonhardt** [PowerShell/Polaris#17]
Consider the following:

`New-StaticRoute -FolderPath "./static" -RoutePath "/public"` 

if there's an `index.html` located in `./static`we should register that as a route to: `/public`. In other words, navigating to `/public` should send the `index.html` file back.

Also, I believe there are a few other defaults out there like `default.html` or `index.htm` we should check for these as well and pick one to become the default if there are multiple options.

**Comment by bateskevin** [comment]
I'm gonna try to implement this. Just forked the repo :)

**Comment by tylerl0706** [comment]
Awesome! Let us know if you need help 😁 should be relatively straightforward.

**Comment by tylerl0706** [comment]
Sorry for the delay. I'm doing some traveling through SE Asia.

When a default file is tracked, it should create the route to the default file AND all the files it contains. For example, consider the following folder structure:

/MyStaticWebsite/
- index.html
- style.css

Where `index.html` references `style.css`. We need a route created for both `index.html` and `style.css` so that  `style.css` can be exposed for `index.html`

What we want is to continue creating routes for all the files in a folder but in addition to that, if we have a default file in the folder we are serving, we should add an additional route for that

**Comment by tylerl0706** [comment]
Does that make sense?

**Comment by tylerl0706** [comment]
P.s. Ill take a look at the PR when I get back from vacation 😊

**Comment by bateskevin** [comment]
Don't worry no need to hurry :) Enjoy PSConf Asia!
